helmValuesRepoURL: https://github.com/cilasbeltrame/argocd-example-apps-deployment-overrides
helmValuesTargetRevision: main
helmChartsRepoURL: https://github.com/cilasbeltrame/argocd-example-apps
helmChartsTargetRevision: master
